import reglas

reglas = reglas.Reglas()

reglas.jugar()


# HAY QUE ASEGURARSE DE DEVOLVER EL SIMBOLO DEL PATRÓN EN LAS FUNCIONES QUE DETECTAN PATRONES, ALMACENARLOS EN LISTA DE LISTAS, PARA ASÍ RECORRERLAS Y CONSULTAR LOS DICCIONARIOS.
